### PR TITLE
Distribute power-assert.d.ts(index.d.ts) type definition files using npm

### PR DESCRIPTION
**Pull request by falsandtru**
Enhanced node package distribute system. Distribute package with `.d.ts` type definition files using npm.
https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages

Type definition files might well survive even after typescript died.
http://mozaic.fm/post/96461640633/8-altjs

### CODE REVIEW

**Comment by twada** [comment]
@falsandtru Thank you for your pull-req!

Since this is a relatively bigger patch, and I don't know much about TypeScript, I would like @vvakame and @teppeis to review this pull-req.

Would you review this PR? > @vvakame @teppeis

**Comment by vvakame** [comment]
I think @twada should be reject this pull request if @twada can't review about .d.ts.
DefinitelyTyped give maintainance for all .d.ts. it is useful for npm package owner who is not TS user.

**Comment by falsandtru** [comment]
DefinitelyTyped is too large project because many pull requests are left unused. `.d.ts` files should divided and ruled the management and maintainance model. So Microsoft created the new model. We should shift to the new model and self-controllable smart eco system. I want this model if @twada can. By the way, I thought of a good idea. Please wait a few days. I show interesting things.

**Comment by teppeis** [comment]
It's trade-off. Hosting index.d.ts ourself is nice for TypeScript users because they don't have to take care of DefinitelyTyped repo additionally.

However, this PR includes tripleslash that is NOT allowed in index.d.ts.

> error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.

In [Typings for npm packages · Microsoft/TypeScript Wiki](https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages "Typings for npm packages · Microsoft/TypeScript Wiki")

> Typings file should:
> * be a .d.ts file
> * be an external module
> * not have triple-slash references

Before power-assert itself, the dependencies (empower and power-assert-formatter) should host their own index.d.ts. Then power-assert can import them.

**Comment by falsandtru** [comment]
Yes. My tripleslash is temporary measures because we cannot resolve type definition dependencies only in this repository. I will resolve this problem in the future. This PR's target is to resolve the hosting(distribute) and maintainance(care) problem.

**Comment by falsandtru** [comment]
Fixed email of commit metadata. And I cancel my idea because need an other server for security.

**Comment by twada** [comment]
Hi @falsandtru , @vvakame and @teppeis ,
Thank you so much for your discussion, and sorry for my late response.

> And I cancel my idea because...

Okay, I'm going to close this pull-req for now.

However, your suggestion make me think about TypeScript users a lot.
I hope power-assert to be convenient to both JavaScript users and TypeScript users.
Hosting `.d.ts` may be a solution, so someday we host type definitions by ourselves.

Thank you for your pull request!
Please feel free to send us more requests.

**Comment by falsandtru** [comment]
Oh it is not means this pull request. Please continue.

**Comment by falsandtru** [comment]
ping @twada

**Comment by twada** [comment]
@falsandtru I'm so sorry for my very late response.

Today I have a conversation with some TS users, and now I'm going to accept your suggestion.
However, I cannot accept your pull-req As-Is, since this PR should solve some more problems that @teppeis pointed out.

So, please wait a few days.
I'll show you an update direction of this pull-req.

**Comment by falsandtru** [comment]
Okay, I thought that this is my strongest pull-req(without behind-the-scenes maneuvering).

**Comment by falsandtru** [comment]
Sample: I support typings as an external module completely on my npm package. You can check external module typings.
https://github.com/falsandtru/arch-stream/tree/v0.0.11

**Comment by falsandtru** [comment]
Fixed @teppeis specified problems. This commit need typings of depended npm packages. Please reopen to show my fixed commit.

**Comment by twada** [comment]
@falsandtru Sorry for my late response.

> Fixed @teppeis specified problems. This commit need typings of depended npm packages. Please reopen to show my fixed commit.

Okay, I'll reopen this PR. Looking forward to see your update.

**Comment by vvakame** [comment]
I want to confirm what is the goal of this pull request?
I think `We want to use power-assert simply in commonjs module context.`. isn't it?
My recommend is along the TypeScript team intention. 

https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages#typings-file-should

**Comment by falsandtru** [comment]
My goal: https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages

If this pull request has a technical problem, I have some ways for resolution. Please tell me your wants.

**Comment by vvakame** [comment]
sounds good. We are sharing a the goal. :smile_cat: 
My opinition is same as teppeis one. https://github.com/power-assert-js/power-assert/pull/29#issuecomment-145601018

> Before power-assert itself, the dependencies (empower and power-assert-formatter) should host their own index.d.ts. Then power-assert can import them.

We should distributed index.d.ts to empower, power-assert-formatter and power-assert.
index.d.ts should external module. not ambient external module.

https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages#typings-file-should
> be an external module

https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#12.2
I think ambient module declaration is not strict equals to external module.

**Comment by falsandtru** [comment]
> My opinition is same as teppeis one. #29 (comment)

I resolved that problem. This resolution refer to external modules directly. Please review again.
https://github.com/power-assert-js/power-assert/pull/29/files.

> index.d.ts should external module. not ambient external module.

I'll fix module design if @twada want.

Sample:

```ts
// power-assert.d.ts
declare function assert(value:any, message?:string): void;
declare namespace assert {
  ...
}
// index.d.ts
import "./power-assert";
export default assert;
```

Not ambient external module is strict, but not good design for model case. Maybe many non-typescript node module developers cannot/doesn't design own .d.ts file.

DefinitelyTyped:

- can update from DefinitelyTyped
- hosted by DefinitelyTyped

```ts
// foo.d.ts
declare namespace foo {
  export var fizz;
}
declare module "foo" {
  export default foo;
  export var fizz: typeof foo.fizz;
}
```

External modules (compatible):

- can update from DefinitelyTyped
- hosted by owner or DefinitelyTyped

```ts
// foo.d.ts
declare namespace foo {
  export var fizz;
}
declare module "foo" {
  export default foo;
  export var fizz: typeof foo.fizz;
}
// index.d.ts
import "./foo.d.ts";
export * from "foo";
export {default} from "foo";
```

External modules (strict):

- cannot update from DefinitelyTyped
- hosted by owner

```ts
// foo.d.ts
declare namespace foo {
  export var fizz;
}
// index.d.ts
import "./foo.d.ts";
export default foo;
export var fizz: typeof foo.fizz;
```

I recommend compatible design.

**Comment by falsandtru** [comment]
And @vvakame please read this point: http://qiita.com/vvakame/items/72d22e33632178f7db24#comment-482f292bbd35e004c74e

**Comment by twada** [comment]
@falsandtru @vvakame @teppeis 

Thanks you for your discussions. Thank you all, really.

Decided. I close this pull-req for now.

I think this PR is not bad. Hosting `index.d.ts` will be one of the future direction we select.

However I close this PR because,

1. TypeScript spec and implementation of hosting typings in npm module is young, not stable, not mature enough. There should be only one true way to describe and provide type definition.
2. I (@twada) am not a TypeScript user, so I cannot review deep technical details of this PR for now. It's my fault.
3. There are some other gradual typing solutions like Flowtype. TypeScript is not a dominant language yet.

So, I want to wait for time-proven and well-documented best practices of hosting type definitions. I'll reopen this or send another pull-req when the time for hosting typings has come.

I'm so so sorry for closing this pull-request.

Thanks.

**Pull request closed without merging**
