### PR TITLE
Run tests on Chrome and Firefox browser

### PR DESCRIPTION
**Pull request by falsandtru**

### CODE REVIEW

**Comment by falsandtru** [comment]
@twada This PR needs a following update.

https://github.com/power-assert-js/karma-espower-preprocessor/pull/1

**Comment by twada** [comment]
@falsandtru Wow! Thanks a lot!!
I'll merge this one when the related PR lands.

**Comment by falsandtru** [comment]
@twada I fixed this PR, so you can merge now.

**Comment by twada** [comment]
LGTM again 👍
Thank you for your great contribution!

**Pull request merged**
