### PR TITLE
feat(assert): use `core-assert` in browser field (fix #45)

### LINKED ISSUE #45: webpack use the legacy assert ( `deepStrictEqual` is not a function )
when use the `power-assert@1.3.1` from `webpack@1.12.14` / `babel-loader@6.2.4`, doesn't have the `deepStrictEqual`, it seems old `assert` is used.

```js
import assert from 'assert';
import moduleName from '../src';

describe('moduleName', () => {
  it('spec1', () => {
    assert.deepEqual(moduleName(), { foo: null });// pass
    assert.deepStrictEqual(moduleName(), { foo: null });// error
  });
});
```

simulation environment: https://github.com/59naga/boilerplate-browser-babel

```bash
git clone https://github.com/59naga/boilerplate-browser-babel
cd boilerplate-browser-babel
git checkout 4804fd5432c626268ca2f148bc58e15bed7c0ec5

npm install
node -v && npm -v
# v5.10.0
# 3.8.3
npm test
# TypeError: _powerAssert2.default.deepStrictEqual is not a function
#        at Context.<anonymous> (/Users/59naga/Downloads/boilerplate-browser-babel/test/index.js:71:28 <- webpack:///test/index.js:10:11)
```

one workaround,  frozen the version of `assert` in `4.1.2` using the [core-assert](https://github.com/59naga/power-assert/commit/1046e66da2a2c5be16988620ee68b43613450d33).

```bash
npm install 59naga/power-assert
npm test
# ...
# AssertionError:   # test/index.js:11
#
#   assert.deepStrictEqual(moduleName(), { foo: null })
#                          |                 |
#                          |                 Object{foo:null}
#                          Object{foo:undefined}
```

other than this, would you have any good solution?

> 英語に自信がないので、翻訳前の日本語も残しておきます。
> `webpack`/`babel-loader`から`power-assert`を使用すると、`deepStrictEqual`を持たない、古い`assert`が使用されるようです。
> 解決方法の一つとして、[core-assert](https://github.com/59naga/power-assert/commit/1046e66da2a2c5be16988620ee68b43613450d33)に依存し、`assert`のバージョンを`4.1.2`に固定する方法があります。
> これ以外で、何か良い解決方法はご存知でしょうか？

### PR DESCRIPTION
**Pull request by 59naga**
> [replace specific files - advanced / defunctzombie/package-browser-field-spec](https://github.com/defunctzombie/package-browser-field-spec\#replace-specific-files---advanced)

that redefines the polyfill function, enable use the `deepStrictEqual`! 👍

### CODE REVIEW

**Comment by 59naga** [comment]
test on the `TravicCI` has failed. however it works well with [my environment](). (maybe: in pre-built power-assert it has failed to shaping).

**Comment by twada** [comment]
@59naga Thanks! Okay I'll investigate this PR on my laptop too.

**Comment by twada** [comment]
Hmm, something is strange. Tests are failing on Firefox and Safari too (it works on Chrome). I'll digging in more deeply.

**Comment by twada** [comment]
I've found the problem. Tests are failing since `core-assert` uses [Error.captureStackTrace](https://github.com/sindresorhus/core-assert/blob/master/index.js#L77).
In short, `core-assert` is not for browsers.

**Comment by twada** [comment]
@59naga Just released [power-assert 1.4.0](https://github.com/power-assert-js/power-assert/blob/master/CHANGELOG.md#140-2016-05-06). Would you try it?

**Comment by 59naga** [comment]
thanks @twada ! `deepStrictEqual`/`notDeepStrictEqual` work in [my webpack environment](https://github.com/59naga/boilerplate-browser-babel/blob/master/test/index.js) :beer:.

**Comment by twada** [comment]
@59naga I'm very glad to hear that 😺 
Would you close this PR?

**Comment by 59naga** [comment]
yep

**Comment by twada** [comment]
@59naga Thanks! And thank you for using power-assert.
Please feel free to send us issues and PRs when you find some improvements.

**Pull request closed without merging**
