### PR TITLE
chore(travis): run tests on Linux and OSX

### PR DESCRIPTION
**Pull request by falsandtru**

### CODE REVIEW

**Comment by twada** [comment]
@falsandtru Wow this is great!! 👍

**Comment by twada** [comment]
Merged. Thanks!

**Comment by teppeis** [comment]
I think we no longer needs to support Node v0.10 ([the maintenance end is 2016-10-31](https://github.com/nodejs/LTS) and [the build is slow](https://travis-ci.org/power-assert-js/power-assert/builds/172174645)).
Instead, testing in Node v7 is good for future.

@twada Do you have any support policy?

**Comment by twada** [comment]
@teppeis Ah, we need to declare support policy. Right.

**Pull request merged**
