### PR TITLE
Support standard style definitions of transpirable es6 modules

### PR DESCRIPTION
**Pull request by falsandtru**
Please also review with other owners.

### CODE REVIEW

**Comment by twada** [comment]
@falsandtru Thank you for your PR!!
Would you add some more explanation or reference URL for this PR?

**Comment by falsandtru** [comment]
For example, http://www.2ality.com/2015/12/babel-commonjs.html

**Comment by twada** [comment]
@falsandtru Thanks!

@teppeis @vvakame @azu Any thoughts?

**Comment by falsandtru** [comment]
Another, how about #36 ?

**Comment by twada** [comment]
@falsandtru Sorry for my late response about #36, replied and marked as `wontfix` for now though...

**Comment by falsandtru** [comment]
Also TypeScript emits:

```ts
    Object.defineProperty(exports, "__esModule", { value: true });
```

**Comment by vvakame** [comment]
sorry for late reply. LGTM. I think we can merge this PR.

**Comment by twada** [comment]
@vvakame Thank you for your review!

@teppeis Would you review this too?

**Comment by falsandtru** [comment]
Improved to `Object.defineProperty(exports, "__esModule", { value: true });`.

**Comment by twada** [comment]
@falsandtru Thank you for your update.
Would you use [define-properties](https://www.npmjs.com/package/define-properties) for older browsers?

**Comment by falsandtru** [comment]
@twada Changed to use define-properties.

**Comment by twada** [comment]
@falsandtru LGTM.
Now we are going to merge and cut a new release soon.
Thank you for your contribution!

**Comment by falsandtru** [comment]
All right.

log: change double quotes to single quotes.

**Comment by twada** [comment]
Released as [power-assert 1.3.0](https://github.com/power-assert-js/power-assert/blob/master/CHANGELOG.md#130-2016-03-09). Thank you for your contribution and reviews!

**Pull request merged**
